<div class="mt-3 miko-tab-contain">
	<div class="miko-tab-main">
		<a class="miko-tab-item mr-1 mb-1 {{(!isset($request->tinhtrang))?'miko-tab-active':''}}" href="{{route('admin.order.show',['man'])}}"><i class="mr-2 fal fa-clipboard-list"></i> Tất cả ({{(isset($itemCountOrder) && $itemCountOrder['allFull']>0) ? $itemCountOrder['allFull'] : 0}})</a>
		<a class="miko-tab-item mr-1 mb-1 {{(isset($request->tinhtrang) && $request->tinhtrang==1)?'miko-tab-active':''}}" href="{{route('admin.order.show',['man','tinhtrang'=>1])}}"><i class="mr-2 fal fa-shopping-bag"></i> Mới đặt ({{(isset($itemCountOrder) && $itemCountOrder['allMoidat']>0)?$itemCountOrder['allMoidat']:0}})</a>
		<a class="miko-tab-item mr-1 mb-1 {{(isset($request->tinhtrang) && $request->tinhtrang==2)?'miko-tab-active':''}}" href="{{route('admin.order.show',['man','tinhtrang'=>2])}}"><i class="mr-2 far fa-clipboard-list-check"></i> Đã xác nhận ({{(isset($itemCountOrder) && $itemCountOrder['allDaxacnhan']>0)?$itemCountOrder['allDaxacnhan']:0}})</a>
		<a class="miko-tab-item mr-1 mb-1 {{(isset($request->tinhtrang) && $request->tinhtrang==3)?'miko-tab-active':''}}" href="{{route('admin.order.show',['man','tinhtrang'=>3])}}"><i class="mr-2 fal fa-truck"></i> Đang giao ({{(isset($itemCountOrder) && $itemCountOrder['allDanggiao'])?$itemCountOrder['allDanggiao']:0}})</a>
		<a class="miko-tab-item mr-1 mb-1 {{(isset($request->tinhtrang) && $request->tinhtrang==6)?'miko-tab-active':''}}" href="{{route('admin.order.show',['man','tinhtrang'=>6])}}"><i class="mr-2 fal fa-undo"></i> Đang chuyển hoàn ({{(isset($itemCountOrder) && $itemCountOrder['allDangchuyenhoan']>0)?$itemCountOrder['allDangchuyenhoan']:0}})</a>
		<a class="miko-tab-item mr-1 mb-1 {{(isset($request->tinhtrang) && $request->tinhtrang==7)?'miko-tab-active':''}}" href="{{route('admin.order.show',['man','tinhtrang'=>7])}}"><i class="mr-2 fal fa-truck-couch"></i> Đã chuyển hoàn ({{(isset($itemCountOrder) && $itemCountOrder['allDachuyenhoan']>0)?$itemCountOrder['allDachuyenhoan']:0}})</a>
		<a class="miko-tab-item mr-1 mb-1 {{(isset($request->tinhtrang) && $request->tinhtrang==4)?'miko-tab-active':''}}" href="{{route('admin.order.show',['man','tinhtrang'=>4])}}"><i class="mr-2 fal fa-clipboard-check"></i> Hoàn thành ({{(isset($itemCountOrder) && $itemCountOrder['allDagiao']>0)?$itemCountOrder['allDagiao']:0}})</a>
		<a class="miko-tab-item mr-1 mb-1 {{(isset($request->tinhtrang) && $request->tinhtrang==5)?'miko-tab-active':''}}" href="{{route('admin.order.show',['man','tinhtrang'=>5])}}"><i class="mr-2 fal fa-calendar-times"></i> Đã hủy ({{(isset($itemCountOrder) && $itemCountOrder['allDahuy']>0)?$itemCountOrder['allDahuy']:0}})</a>
	</div>
</div>